### ISSUE TITLE
When this package is used in a project without a packages.config file the sqllite will not be copied to the ouput directory

### ISSUE THREAD

**Issue by sanderaernouts** [natemcmaster/libsqlite3-package#12]
We use [Paket](https://github.com/fsprojects/Paket) as an alternate NuGet client and because of this out projects do not have a packages.config file anymore. When we converted one of our solution we ran into issues with the SQLite.Native package. It did not copy the required DLL's to the output directory. 

I also tested this with the new[ \<PackageReference\>](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) format that is replacing packages.config and got the same results. No SQLite DLL's are copied to the bin folder:
![image](https://user-images.githubusercontent.com/6184673/36961071-fb5e0368-2049-11e8-8db3-b2e43584b7a3.png)
![image](https://user-images.githubusercontent.com/6184673/36961040-d61b0f56-2049-11e8-8e30-a451a171afc9.png)

This happens because of these conditions in the props files:
![image](https://user-images.githubusercontent.com/6184673/36961157-53e1902c-204a-11e8-8a62-6a705c91914d.png)

**Comment by natemcmaster** [comment]
This sounds like a bug in Paket to me. These item groups were added to as a workaround for features not added until NuGet 3. In NuGet 3+, the files in `runtime/$rid/native/` are automatically copied to the build output folder. It sounds to me like Paket may not have implemented this feature.

**Comment by sanderaernouts** [comment]
> In NuGet 3+, the files in runtime/$rid/native/ are automatically copied to the build output folder.

I wasn't aware of that.

I think the only reason the package worked for our project before was because a packages.config file was present so maybe our project isn't targeting the right runtimes. So let's forget about Paket for now. Can you explain the rationale behind the condition statements that check if a packages.config files exists? Is this to detect "old" style and does this runtime/$rid/native feature you mention only work for .NET Core projects or also for normal projects?

**Comment by natemcmaster** [comment]
No worries, the feature is lacking good documentation. I wrote a little bit about this feature here https://www.natemcmaster.com/blog/2016/05/19/nuget3-rid-graph/. You can also read more about it here: https://github.com/dotnet/corefx/tree/master/pkg/Microsoft.NETCore.Platforms#runtime-ids

What does your project look like? I might be able to help. It's possoble it's a Paket bug, or that you're just missing a setting.

The rationale was we needed a way to detect if the project was using NuGet 2. The existence of packages.config or packages.$(ProjectName).config was the only thing we could come up with. Unfortunately, NuGet didn't introduce MSBuild properties for detecting the NuGet version until NuGet 4.

The way `runtime/$rid/native` feature works in .NET Core projects is a little bit of magic. You won't actually see sqlite3.dll in your output folder when you build.  .NET Core is able to resovle the `sqlite3.dll` file from the NuGet cache when running the output in `dotnet build`. This is a development-only scenario. When you execute `dotnet publish`, you should see a folder named "runtimes" in the publish output.

This feature should also work in .NET Framework projects using the new "Sdk" style projects (VS 2017). At the time this package was released, support for PackageReference in "classic" .csproj projects (i.e. VS 2015 and before) was not on the radar, so I'm not sure this works there.

**Comment by sanderaernouts** [comment]
That might explain it. We use "classic" .csproj projects, now with Paket and thus we have paket.reference files but this is essentially similar to the using packages.config files. I tested your package with a classic .csproj with PackageReference and that does not seem to work as well.

Our workaround for now is to place an empty packages.config file in the project directory so the package "thinks" it is in a classic csproj with packages.config.

Is there an MSBuild way to detect if a project is .NET Core? Else can't we introduce an MSBuild variable that can force the copy behaviour by adding it into the condition. I know this is not ideal but it is better then having an empty packages.config file when you are using different ways to reference packages such as PackageReference or Paket in classic projects.

**Comment by natemcmaster** [comment]
Yes, there are MSBuild ways to detect all of these kinds of configurations. Like I mentioned, there has been rapid churn in this part of the product over the last 18 months. I don't actually work on this part of the product anymore, but if you want dig in and make a recommendation that helps make this package work with Paket in classic csproj while preserving .NET Core, Sdk-style projects, PackageReference, etc., I'll take a look and see if I can get the sqlite guys to update the package.

**Comment by sanderaernouts** [comment]
@natemcmaster how about just adding an MSBuildVariable like SQLiteNative_ForceCopyNativeAssembliess with an Or to the condition for the ItemGroups? It will allow consumers of the package to force the required behavior when in an old CSPROJ with package reference or with Paket. 

It's still a workaround, but a better one than having an empty packages.config file in the project root directory. The empty packages.config file might give the impression that packages.config is still used by the project for managing dependencies which is not the case and it might even confuse NuGet.

**Comment by natemcmaster** [comment]
Yeah, I would be okay to that. Not sure when I could get this released, though. I'll have to reach out to the SQLite team. I technically don't own the SQLite packages on nuget.org.
